container:
  image: alpine:latest

main_task:
  clone_script: echo 'clone'
  script: sleep 5

task:
  clone_script: echo 'clone'
  matrix:
    name: foo
    name: bar
  execution_lock: lock
  script: sleep 2

