task:
  container:
    image: redis:latest
    additional_containers:
      - name: redis
        image: redis:latest
        port: 6379
  script:=
    - redis-cli incr foo
    - redis-cli incr foo
    - redis-cli get foo
