task:
  name: Test Things 🎉
  container:
    dockerfile: .ci/Dockerfile
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Bye!"
    
