task:
  experimental: true
  matrix:
    - name: Test Things on x86 🎉
      container:
        image: alpine:latest
  
  sleep_script: 
    - echo "Hello!"
    - echo "Bye!"
  env_script: printenv
    
