task:
  matrix:
    - name: Test Things on x86 🎉
      container:
        image: alpine:latest
    - name: Test Things on Arm 🎉
      arm_container:
        image: alpine:latest
  build_script: echo $CIRRUS_BUILD_NUMBER
  sleep_script: 
    - echo "Hello!"
    - sleep 15
    - echo "Bye!"
    
