task:
  name: Test Things 🎉
  persistent_worker: {}
  printenv_script: printenv
  version_script: xcodebuild -version
  flutter_script: flutter doctor
  sleep_script: 
    - echo "Hello!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
