task:
  name: Test Things 🎉
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-next
    platform: linux 
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Buy!"
    
