aws_credentials:
  role_arn: arn:aws:iam::471777771536:role/CirrusOIDCTest-Role-1H7XA69P793Q5

task:
  name: Test Things on EKS 🎉
  eks_container:
    region: us-east-2
    cluster_name: cirrus-arm-cluster
    dockerfile: Dockerfile
    builder_image: ami-0ea01e64891fb03be
    builder_role: cirrus-builder-TEST2
    builder_instance_type: c7g.xlarge
    architecture: arm64

  sleep_script:
    - echo "Hello!"
    - sleep 9
    - echo "Bye!"
