task:
  container:
    image: mysql:latest
    additional_containers:
      - name: mysql
        image: mysql:latest
        port: 3306
        env:
          MYSQL_ROOT_PASSWORD: ""
  connection_script: mysql --user=root --host=localhost -e exit
