aws_credentials:
  role_arn: arn:aws:iam::471777771536:role/CirrusOIDCTest-Role-1H7XA69P793Q5
    
ec2_task:
  ec2_instance:
    image: ami-073a06fe642e0b4e9
    platform: windows
    region: us-east-2
    type: m5zn.2xlarge
  script: echo %PATH%
