task:
  name: Integration Tests (x86)
  container:
    image: cirrusci/android-sdk:30
    kvm: true
    additional_containers:
      - name: emulator
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
        port: 5555
        cpu: 2
        memory: 4G
  adb_script:
    - adb devices
    - adb wait-for-device
    - adb devices
