aws_credentials: ENCRYPTED[c3a6337e976cae5c986b17ee7bd8afb87aaa9665c17c25d2aa990049779ac1a257a3d9dd99d98b63e8d503ed37dfdd07]

task:
  name: Test Things on EKS 🎉
  eks_container:
    region: us-east-2
    cluster_name: cirrus-arm-cluster
    dockerfile: Dockerfile
    builder_image: ami-0ea01e64891fb03be
    builder_role: cirrus-builder
    builder_instance_type: c7g.xlarge
    architecture: arm64

  sleep_script:
    - echo "Hello!"
    - sleep 9
    - echo "Bye!"
