task:
  name: Test Things 🎉
  container:
    image: alpine:latest
    cpu: 0.1
    memory: 128Mb
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
