build_task:
  container:
    image: alpine:latest
  foo_script: echo "Foo"
  sleep_script: sleep 120

task:
  name: Deploy to Staging
  depends_on: build
  trigger_type: manual
  container:
    image: alpine:latest
  deploy_script: echo "Deploy"
