container:
  image: debian:10-slim

task:
  clone_script: echo 'clone'
  dependencies_script: 
    - apt-get update
    - apt-get install -y --no-install-recommends procps
  test_script:
    - bash -c '/bin/sleep 5 & disown'
    - ps -eo ppid,pid,user,cpu,rss,stat,start,command
    - sleep 10
    - ps -eo ppid,pid,user,cpu,rss,stat,start,command
