task:
  name: Test Things 🎉
  container:
    image: alpine:latest
  result_cache:
    folder: result
  create_script:
    - mkdir result
    - cd result
    - dd if=/dev/urandom of=data.bin bs=10M count=10
