netbsd_task:
  compute_engine_instance:
    image_project: pg-ci-images-dev
    image: family/pg-ci-netbsd-9-2
    platform: netbsd
    cpu: 4
    memory: 4G
  
  script: 
    - echo "Hello!"
    - sleep 4
    - echo "Bye!"
    
