task:
  name: Test Things 🎉
  container:
    image: alpine:latest
    cpu: 0.1
    memory: 64Mb
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - sleep 4
    - sleep 5
    - echo "Buy!"
    
