task:
  name: Test Things 🎉
  container:
    image: alpine:latest
  stateful: true
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Buy!"
    
