task:
  name: Test Things 🎉
  osx_instance:
    image: catalina-xcode
  env:
    CIRRUS_LOG_TIMESTAMP: true
  sleep_script: 
    - echo "Hey!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
  script: flutter doctor
