task:
  name: Test Softnet
  env:
    CIRRUS_DISPLAY: 2000x1000
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - brew tap jakehilborn/jakehilborn && brew install displayplacer
    - displayplacer list
