task:
  container:
    image: redis:latest
    additional_containers:
      - name: redis
        image: redis:latest
        port: 6379
  script:
    - redis-cli 
    - redis-cli inc foo
    - redis-cli inc foo
    - redis-cli get foo
