task:
  alias: tests
  matrix:
    - name: Test Things on x86 🎉
      container:
        image: golang:latest
    - name: Test Things on Arm 🎉
      arm_container:
        image: golang:latest
  measure_script:
    - COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
    - NOW_TIMESTAMP=$(date +%s)
    - DURATION=`expr $NOW_TIMESTAMP - $COMMIT_TIMESTAMP`
    - echo "Duration to start: $DURATION"
  build_script: echo $CIRRUS_BUILD_NUMBER
  time_script: date +%s
  sleep_script: |
    for i in {1..5}
    do
       sleep $i
       echo "Step $i"
    done

finisher_task:
  depends_on: tests
  container:
    image: golang:latest
  sleep_script: |
    for i in {1..5}
    do
       sleep $i
       echo "Step $i"
    done
