aws_credentials:
  role_arn: arn:aws:iam::471777771536:role/CirrusTest3-Role-BX3Y3TKOYTPQ
  role_session_name: cirrus
  region: us-east-2
    
ec2_task:
  experimental: true
  ec2_instance:
    image: ubuntu/images/*ubuntu-jammy-22.04-arm64-server-*
    architecture: arm64
    region: us-east-2
    type: a1.medium
  touch_script: touch zero.txt
  junit_artifacts:
      path: "zero.txt"
    
