task:
  name: Test Things 🎉
  windows_container:
    image: cirrusci/android-sdk:28-windowsservercore-2019
  env:
    COMPUTE_ENGINE_IMAGE_NAME: windows-docker-builder-v20200813
  sleep_script: sdkmanager --help
