task:
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-0
      image_family: freebsd-11-3
      image_family: freebsd-10-4
  echo_script: echo $PATH 
