task:
  name: Test Things 🎉
  arm_container:
    image: alpine:latest
    cpu: 0.5
    memory: 256Mb
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Buy!"
    
