task:
  name: Test Things 🎉
  persistent_worker:
    isolation:
      parallels:
        image: catalina-xcode-11.3.1
        user: admin
        password: admin
        platform: darwin
  printenv_script: printenv
  version_script: xcodebuild -version
  sleep_script: 
    - echo "Hello!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
