task:
  windows_container:
    image: cirrusci/windowsservercore:visualstudio2019-2021.12.07
  install_script: choco install nodejs
  version_script:
    - refreshenv
    - npm --version
    - npx --version
