task:
  name: Test Things 🎉
  persistent_worker:
    isolation:
      parallels:
        image: big-sur-base
        user: admin
        password: admin
        platform: darwin
  printenv_script: printenv
  version_script: sleep 300
