task:
  name: Test Things 🎉
  arm_container:
    image: alpine:latest
    cpu: 1
    memory: 1G
  arch_script: uname -a
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Buy!"
    
