task:
  name: Test Things on $CIRRUS_ARCH 🎉
  experimental: true
  matrix:
    arm_container:
      image: curlimages/curl:latest
      cpu: 0.5
  try1_script: 
    - curl ifconfig.me
    - echo ""
    - curl --verbose https://rvm.io/images/rvm-logo-all-happy.png -O
  always:
    sleep_script: sleep 20
    try2_script: 
      - curl ifconfig.me
      - echo ""
      - curl --verbose https://rvm.io/images/rvm-logo-all-happy.png -O
