task:
  name: Test Things 🎉
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    image: family/freebsd-13-0
    platform: freebsd
    cpu: 4
    memory: 16G
    nested_virtualization: false
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - echo "Buy!"
    
