task:
  name: Test Things 🎉
  container:
    image: alpine:latest
  env:
    CIRRUS_LOG_TIMESTAMP: true
  sleep_script: 
    - echo "Hey!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
  printenv_script: printenv
