azure_credentials: ENCRYPTED[ee851768a77bcc552ff3dd14a75eaad1270c61b84f86183d30b5d8dcd25081f5a1d4089c0fb2c71b3f64a2fb1294ddf0]

task:
  name: Test Things 🎉
  azure_container_instance:
    image: alpine:latest
    resource_group: CirrusCI
    region: westus
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - sleep 3
    - echo "Buy!"
    
