task:
  name: Test Disk I/O
  matrix:
    experimental: true
    experimental: false
  container:
    image: alpine:latest
  throughtput_script: dd if=/dev/zero of=/tmp/test1.img bs=1G count=10 oflag=direct
  latency_script: dd if=/dev/zero of=/tmp/test2.img bs=512 count=10000 oflag=direct
