freebsd13_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  script:
    - useradd --system --uid 1000 --shell /bin/bash --create-home cirrus
    - adduser cirrus sudo
    - su - cirrus
    - whoami
