task:
  name: Test Things 🎉
  compute_engine_instance:
    image_project: pg-vm-images-aio
    image: family/pg-aio-freebsd-12-2
    platform: freebsd
    cpu: 4
    memory: 8G
  printenv_script: printenv
  sleep_script: sleep 300
    
