task:
  name: Test Things on x86 🎉
  container:
    image: alpine:latest
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    - sleep 1
    - echo "1"
    
