task:
  name: Test Disk I/O
  matrix:
    experimental: true
    experimental: false
  container:
    image: ubuntu:latest
  throughtput_script: dd if=/dev/zero of=/root/testfile bs=1G count=1 oflag=direct
  latency_script: dd if=/dev/zero of=/root/testfile bs=512 count=1000 oflag=direct
