task:
  name: Test Things 🎉
  container:
    image: alpine:latest
    cpu: 1
    memory: 1G
    greedy: true
    additional_containers:
      - name: mysql
        image: circleci/mysql:5.6-ram
        port: 3306
        cpu: 0.25
        memory: 1Gi
  sleep_script: 
    - echo "Hello!"
    - sleep 120
    
