example_task:
  # also happens for `container` though that isn't as important
  # because `docker_builder` exists
  container:
    image: docker:latest
    kvm: true
    additional_containers:
      - name: dockerdaemon
        cpu: 4
        memory: 3G
        image: docker:dind
        port: 2375
        env:
          DOCKER_DRIVER: overlay2
  env:
    DOCKER_HOST: tcp://localhost:2375
  script: docker run ubuntu echo hello
    
