task:
  name: Test Things 🎉
  matrix:
    - container:
        dockerfile: .ci/Dockerfile.linux
    - arm_container:
        dockerfile: .ci/Dockerfile.linux
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 2
    - echo "Bye!"
    
