task:
  name: Test Things 🎉
  container:
    image: alpine:latest
  printenv_script: printenv
  html_artifacts:
    path: redirect.html
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - echo "Buy!"
    
