task:
  name: Public Playground
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    CIRRUS_SHELL: powershell
  script:
    - echo 'Foo'
    - echo 'Bar'
    - echo 'Baz'
