container:
  image: alpine:latest

depends_on_foo_template: &DEPENDS_ON_TEMPLATE
  depends_on:
    - foo

foo_task:
  script: echo foo

bar_task:
  script: echo bar

foobar_task:
  <<: *DEPENDS_ON_TEMPLATE
  depends_on:
    - foo
    - bar
  script: echo foobar
