task:
  name: Test Things 🎉
  experimental: true
  stateful: true
  container:
    image: alpine:latest
    matrix:
      cpu: 1
      cpu: 2
      cpu: 4
  env:
    matrix:
      SHARD: 0
      SHARD: 1
      SHARD: 2
      SHARD: 3
      SHARD: 4
      SHARD: 5
      SHARD: 6
      SHARD: 7
      SHARD: 8
      SHARD: 9
  sleep_script: sleep $((RANDOM % 60))
