task:
  name: Test Things 🎉
  container:
    image: alpine:latest
    cpu: 0.5
    memmory: 256Mb
  printenv_script: printenv
  sleep_script: 
    - echo "Hey!"
    - sleep $((RANDOM % 10))
    - echo "Buy!"
