azure_credentials: ENCRYPTED[707dd01c64856bfa9417bedf09a3ef7f96b9bd2d94b9e25043203647852ce6a9c48e40946ab84042e3a8747cd769d671]

task:
  name: Test Things 🎉
  azure_instance:
    image_reference:
      publisher: MicrosoftWindowsDesktop
      offer: Windows-10
      sku: 20h1-pro
    region: westus
    platform: windows
  script: 
    - ps: Get-Location
    
