task:
  container:
    image: alpine:latest
  change_dir_script:
    - mkdir -p foo
    - cd foo
    - echo "Hello, Bar!" >> bar.txt
    - echo "CIRRUS_WORKING_DIR=$CIRRUS_WORKING_DIR/foo" >> $CIRRUS_ENV
  print_script:
    - cat bar.txt
