docker_builder:
  platform: windows
  os_version: 2019
  version_script: docker --version
  type_script: 
    - echo %username%
    - gcloud auth configure-docker gcr.io
    - type %USERPROFILE%\.docker\config.json
