example_task:
  container:
    image: mysql:latest
    additional_containers:
      - name: mysql
        image: mysql:latest
        port: 3306
        cpu: 1.0
        memory: 512Mi
        env:
          MYSQL_ROOT_PASSWORD: ""
  wait_script: wait 120
  version_script: mysqladmin version -h localhost
    
