task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
  
  sleep_script: 
    - echo "Hello!"
    - sleep 11
    - echo "Bye!"
    
