task:
  name: Test Cache
  experimental: true 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-runner:latest
  test_cache:
    folder: foo
    fingerprint_script:
      - echo $CIRRUS_OS
    populate_script: 
      - mkdir foo
      - cd foo
      - date >> date.txt
