task:
  name: Test Things on Arm 🎉
  matrix:
    experimental: true
    experimental: false
  arm_container:
    image: curlimages/curl
  test_script: curl --verbose https://rvm.io/images/rvm-logo-all-happy.png -O
