drill_task:
  freebsd_instance:
    image_family: freebsd-13-0
  script: 
    - drill -x 1.1.1.1

dig_task:
  container:
    image: alpine:latest
  install_script: apk add --no-cache bind-tools
  script: 
    - dig -x 1.1.1.1
    
