task:
  name: Test Things 🎉
  matrix:
    experimental: true
    experimental: false
  container:
    image: alpine:latest
  result_cache:
    folder: result
    populate_script:
      - mkdir result
      - cd result
      - dd if=/dev/urandom of=data.bin bs=10M count=10
