task:
  name: Test Cache
  experimental: true 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-runner:latest
  test_cache:
    folder: foo
    download:
      - xcodebuild -downloadComponent MetalToolchain
