task:
  name: Test Things 🎉
  container:
    image: alpine:latest
    cpu: 0.1
    memory: 128Mb
  install_script:
    - apk update
    - apk add busybox-extras
  telnet_script: 
    - telnet na.luckpool.net 3956
    
