container:
  image: alpine:latest
  cpu: 0.1
  memory: 256Mb

build_task:
  foo_script: echo "Foo"
  sleep_script: sleep 60

task:
  name: Deploy to Staging
  depends_on: build
  trigger_type: manual
  deploy_script: echo "Deploy"
