task:
  name: Test DNS
  use_compute_credits: true 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  script:
    - networksetup -getdnsservers Ethernet
    - sudo networksetup -setdnsservers Ethernet "Empty"
    - networksetup -getdnsservers Ethernet
