task:
  matrix:
    - name: Test Things on x86 🎉
      container:
        image: alpine:latest
    - name: Test Things on Arm 🎉
      arm_container:
        image: alpine:latest
  touch_script: touch zero.txt
  junit_artifacts:
      path: "zero.txt"
    
