task:
  matrix:
    - name: Test Things on Arm 💪
      arm_container:
        image: alpine:latest
        cpu: 0.5
        memory: 256Mb
    - name: Test Things on x86 🎉
      container:
        image: alpine:latest
        cpu: 0.5
        memory: 256Mb
  
  sleep_script: 
    - echo "Hello!"
    - sleep 8
    - echo "Bye!"
    
