experimental: true

docker_builder:
  build_script: docker --version

pipe:
  experimental: true
  name: Pipe Testing
  steps:
    - image: squidfunk/mkdocs-material:latest
      build_script: mkdocs --version
    - image: raviqqe/liche:latest
      validate_script: /liche --version

task:
  experimental: true
  name: Test Things 🎉
  matrix:
    - container:
        image: alpine:latest
    - container:
        image: alpine:latest
        kvm: true
    - freebsd_instance:
        image_family: freebsd-12-1
  ip_script: curl ifconfig.co
  sleep_script: sleep $((RANDOM % 60))
  
windows_task:
  experimental: true
  windows_container:
    image: cirrusci/windowsservercore:2019
