task:
  matrix:
    - name: Test Things on x86 🎉
      container:
        image: alpine:latest
    - name: Test Things on Arm 🎉
      arm_container:
        image: alpine:latest
  
  sleep_script: 
    - echo "Hello!"
    - sleep 11
    - echo "Bye!"
    
