task:
  name: Test Things on Arm 🎉
  matrix:
    experimental: true
    experimental: false
  arm_container:
    image: curlimages/curl
  try_script: curl --verbose https://rvm.io/images/rvm-logo-all-happy.png -O
  always:
    sleep_script: sleep 60
    try2_script: curl --verbose https://rvm.io/images/rvm-logo-all-happy.png -O
