task:
  name: Test Things 🎉
  container:
    image: alpine:latest
  printenv_script: printenv
  sleep_script: 
    - echo "Hello!"
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - sleep 1
    - echo "Buy!"
    
