aws_credentials:
  role_arn: arn:aws:iam::471777771536:role/CirrusTest3-Role-BX3Y3TKOYTPQ
  role_session_name: cirrus
  region: us-east-2
    
ec2_task:
  ec2_instance:
    image: /aws/service/ecs/optimized-ami/amazon-linux-2/arm64/recommended
    architecture: arm64
    region: us-east-2
    type: a1.metal
  script: echo %PATH%
