task:
  name: Android Emulator (Hardware Accelearated)
  container:
    image: cirrusci/android-sdk:30
    kvm: true
    additional_containers:
      - name: emulator
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
        port: 5555
        cpu: 4
        memory: 8G
  adb_script:
    - adb wait-for-device
    - adb devices
